import React, { useEffect, useRef, useState } from 'react';
import mermaid from 'mermaid';
import './MermaidDiagram.css';

/**
 * MermaidDiagram — Reusable component that renders a Mermaid.js diagram.
 *
 * Props:
 *   - diagramText (string): Raw Mermaid syntax generated by the AI / LLM.
 *     Example:
 *       graph TD
 *         A[Start] --> B[Process]
 *         B --> C[End]
 *
 * The component:
 *   1. Initialises Mermaid once (startOnLoad disabled so React controls rendering)
 *   2. Re-renders the diagram every time `diagramText` changes (i.e. new topic)
 *   3. Shows a loading/fallback message while no diagram text is available
 *   4. Handles invalid Mermaid syntax gracefully
 */

/* Initialise Mermaid once — startOnLoad is false so we render manually */
mermaid.initialize({
  startOnLoad: false,
  theme: 'default',
  securityLevel: 'loose',
  fontFamily: 'inherit',
});

function MermaidDiagram({ diagramText }) {
  const containerRef = useRef(null);
  const [error, setError] = useState(null);
  const [rendering, setRendering] = useState(false);

  /*
   * Diagram refresh happens here:
   * Every time `diagramText` changes (new topic explained by LLM),
   * we clear the previous SVG and ask Mermaid to render the new one.
   */
  useEffect(() => {
    if (!diagramText || !diagramText.trim()) {
      setError(null);
      return;
    }

    let cancelled = false;

    async function renderDiagram() {
      setRendering(true);
      setError(null);

      try {
        /* Generate a unique id so Mermaid doesn't cache stale diagrams */
        const id = `mermaid-${Date.now()}`;

        const { svg } = await mermaid.render(id, diagramText.trim());

        if (!cancelled && containerRef.current) {
          containerRef.current.innerHTML = svg;
        }
      } catch (err) {
        if (!cancelled) {
          setError('Could not render the diagram. The AI may have produced invalid syntax.');
        }
      } finally {
        if (!cancelled) setRendering(false);
      }
    }

    renderDiagram();

    return () => {
      cancelled = true;
    };
  }, [diagramText]);

  /* Show nothing if there is no diagram text at all */
  if (!diagramText || !diagramText.trim()) {
    return (
      <div className="mermaid-diagram result-section card-flat animate-fade-in">
        <h3 className="result-section-title">🗺️ Concept Diagram</h3>
        <p className="mermaid-diagram__message">Diagram will appear here once generated.</p>
      </div>
    );
  }

  return (
    <div className="mermaid-diagram result-section card-flat animate-fade-in">
      <h3 className="result-section-title">🗺️ Concept Diagram</h3>

      {/* Loading state */}
      {rendering && (
        <div className="mermaid-diagram__loading">
          <div className="skeleton" style={{ height: 200, width: '100%' }} />
        </div>
      )}

      {/* Error fallback */}
      {error && !rendering && (
        <p className="mermaid-diagram__message">{error}</p>
      )}

      {/* Rendered SVG is injected here by Mermaid */}
      <div
        ref={containerRef}
        className="mermaid-diagram__canvas"
        style={{ display: rendering || error ? 'none' : 'block' }}
      />
    </div>
  );
}

export default MermaidDiagram;
